#{{- range $i := untilStep 1 ($.Values.amount | int) 1}} # apps per repo
#{{- range $j := untilStep 1 ($.Values.set | int) 1}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-{{ $.Values.amount }}-{{ $.Values.set }}
  namespace: {{ $.Values.argo.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.uid }}'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: dev/ocp{{ $.Values.amount }}/app{{ $.Values.set }}
    repoURL: 'https://github.com/romerobu/app-values' # change url and branch to ocp3/app00/...
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#{{- end }}  
#{{- end }}  