{{- range $i := untilStep 1 ($.Values.amount | int) 1}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-{{ $i }}-{{ $.Values.set }}
  namespace: {{ $.Values.argo.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.uid }}'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    releaseName: jump-app
    path: dev/ocp{{ $.Values.set }}/app{{ $i }} 
    repoURL: 'https://github.com/romerobu/app-values' # change url and branch to ocp3/app00/...
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}  